### ISSUE TITLE
Question : connecting to Fake Sns using the aws-sdk(JS) throws Credentials error

### ISSUE THREAD

**Issue by jeson114** [s12v/sns#35]
The mock service seems to be working with the aws-cli , but i am unable to connect it with by nodejs application after i create an sns instance from the aws-sdk . Asks for creds . I am not sure if i need access_keys to fake sns . Can someone help me out

**Comment by jeson114** [comment]
Ok found the creds in Dockerfile 

AWS_DEFAULT_REGION eu-west-1 
AWS_ACCESS_KEY_ID foo
AWS_SECRET_ACCESS_KEY bar
This information needs to be on the README.md

**Comment by s12v** [comment]
@jeson114, aws-sdk tries to find credentials, and complains when not found. sns-mock does not need credentials. So, basically, you can provide any key/secret to sdk, so that it doesn't complain.

**Comment by jeson114** [comment]
Yea , All the while i assumed that and tried 
```js
aws.config.accessKeyId = '';
aws.config.secretAccessKey ''; 
```
and the empty strings probably caused that complain
Thanks for replying

**Comment by relicmelex** [comment]
@jeson114 can you close this if your issue was resolved?
