### ISSUE TITLE
Use a consistent account id for topic ARN

### ISSUE THREAD

**Issue by jononu** [s12v/sns#38]
Would you be open to accepting a PR to support this? We have some static configurations across our development team and would like the topics to be created with a consistent ARN. Right now it's using timestamp for the account id, which is obviously not consistent.

I was thinking it could pull an environment variable or fall back to the timestamp if the environment variable isn't set.

Let me know what you think.

**Comment by s12v** [comment]
@jononu, I don't think there was a specific reason to use timestamps for ARNs, maybe you can just set static account ID, like `123456789012`

**Comment by jononu** [comment]
@s12v sounds good, incoming PR soon. :)

**Comment by jononu** [comment]
We tried out the 0.3.0 docker image this morning, that image is still generating ARNs with a timestamp. Was 0.3.0 supposed to have the change from PR #39?

I logged into the container and it has an sns.jar from Nov 22nd in it rather than Dec 6th.

If you haven't gotten around to pushing a new image and I'm jumping the gun just let me know. 👍

**Comment by s12v** [comment]
@jononu, no, it's not supposed to be like that. Thanks, I'll check.

**Comment by jononu** [comment]
Any luck figuring it out? We're just trying to decide if we should go ahead and build a custom docker image or wait.

**Comment by s12v** [comment]
@jononu, it should be fixed now, please try the new version 0.3.5. Sorry for the delay

**Comment by relicmelex** [comment]
@jononu Can you please verify this issue was resolved with 0.3.5?
